In [4]:
import pandas as pd
import numpy as np
from pandas import DataFrame, Series

In [2]:
arr1 = np.arange(9).reshape(3,3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.concatenate([arr1,arr1])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.concatenate([arr1,arr1], axis = 1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [8]:
np.concatenate([arr1,arr1], axis = 0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
ser1 = Series([0,1,2], index=['T','U','V'])

In [10]:
ser1

T    0
U    1
V    2
dtype: int64

In [11]:
ser2 = Series([0,1,2,3], index=['W','X','Y','Z'])

In [12]:
ser2

W    0
X    1
Y    2
Z    3
dtype: int64

In [14]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
W    0
X    1
Y    2
Z    3
dtype: int64

In [15]:
pd.concat([ser1,ser2], axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
W  NaN  0.0
X  NaN  1.0
Y  NaN  2.0
Z  NaN  3.0

In [18]:
pd.concat([ser1,ser2], axis=0, keys = ['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  W    0
      X    1
      Y    2
      Z    3
dtype: int64

In [20]:
Dframe1 = DataFrame(np.random.randn(4,3), columns = ['X','Y','Z'])
Dframe2 = DataFrame(np.random.randn(3,3), columns = ['P','Q','R'])

In [22]:
pd.concat([Dframe1,Dframe2])

X         Y         Z         P         Q         R
0  0.342037 -0.281176  0.262002       NaN       NaN       NaN
1  0.926075  0.114318  0.753081       NaN       NaN       NaN
2  1.208333 -0.812557 -1.304799       NaN       NaN       NaN
3  0.517744 -0.397115 -0.358906       NaN       NaN       NaN
0       NaN       NaN       NaN -0.563284  1.216292  1.229344
1       NaN       NaN       NaN -0.236875  1.095310 -2.025974
2       NaN       NaN       NaN -2.122036  0.413186  0.220572

In [23]:
pd.concat([Dframe1,Dframe2], axis=1)

X         Y         Z         P         Q         R
0  0.342037 -0.281176  0.262002 -0.563284  1.216292  1.229344
1  0.926075  0.114318  0.753081 -0.236875  1.095310 -2.025974
2  1.208333 -0.812557 -1.304799 -2.122036  0.413186  0.220572
3  0.517744 -0.397115 -0.358906       NaN       NaN       NaN

In [24]:
pd.concat([Dframe1,Dframe2], ignore_index=True)

X         Y         Z         P         Q         R
0  0.342037 -0.281176  0.262002       NaN       NaN       NaN
1  0.926075  0.114318  0.753081       NaN       NaN       NaN
2  1.208333 -0.812557 -1.304799       NaN       NaN       NaN
3  0.517744 -0.397115 -0.358906       NaN       NaN       NaN
4       NaN       NaN       NaN -0.563284  1.216292  1.229344
5       NaN       NaN       NaN -0.236875  1.095310 -2.025974
6       NaN       NaN       NaN -2.122036  0.413186  0.220572